---
title: "General Notes"
author: "Zelin Liu"
date: "9/23/2020"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(rvest)
library(ggplot2)
library(tidyverse)
library(dbplyr)
library(rvest)
library(janitor)
library(shiny)
library(ggforce)
library(readr)
library(readxl)
library(priceR)
```

## Scraping Data from Congress.gov (Page 1)
```{r}
url1 <- paste0("https://www.congress.gov/search?q=",
              "{%22source%22:%22treaties%22}",
              "&searchResultViewType=expanded&pageSort=actionAsc&pageSize=250")
url1_treaty <- read_html(url1)

# Website scraping

#body_nodes1 <- url1_treaty %>%
#  html_node("body") %>%
#  html_children()

treaty1_names <- url1_treaty %>%
  html_nodes("body") %>%
  xml_find_all("//span[contains(@class, 'result-heading')]") %>%
  html_text()
treaty1_values_all <- url1_treaty %>%
  html_nodes("body") %>%
  xml_find_all("//span[contains(@class, 'result-item')]") %>%
  html_text()

# Cleaning up "\n" and large space gaps

treaty1_values_notext <- str_subset(treaty1_values_all,
                                   pattern = "Text of Treaty Document",
                                   negate = TRUE)
treaty1_notext_1spaces <- str_replace(treaty1_values_notext,
                                     pattern = "\n        ", replacement = "")
treaty1_notext_2spaces <- str_replace(treaty1_notext_1spaces, 
                                     pattern = "\n        ", replacement =  " ")
treaty1_notext_3spaces <- str_replace(treaty1_notext_2spaces,
                                     pattern = "Document Type:\n",
                                     replacement = "")
treaty1_notext_4spaces <- str_replace(treaty1_notext_3spaces,
                                     pattern = "\n", replacement = "")
treaty1_notext_5spaces <- str_replace(treaty1_notext_4spaces,
                                     pattern = "TXT\n", replacement = "")
treaty1_notext_6spaces <- str_replace(treaty1_notext_5spaces,
                                     pattern = "\n            ",
                                     replacement = "")
treaty1_notext_7spaces <- str_replace(treaty1_notext_6spaces,
                                     pattern = "\n", replacement = "")

# Setting up data for making a vector

treaty1_action0 <- str_subset(treaty1_notext_7spaces, 
                              pattern = "Latest Senate Action")

type_NAMark <- str_subset(treaty1_notext_7spaces, pattern = "Date Received", 
           negate = TRUE)[c(TRUE, FALSE)]
type_half <- str_subset(type_NAMark, pattern = "Treaty")[c(TRUE, FALSE)]

type_indices <- which(str_detect(type_NAMark, pattern = "Treaty"))
type_indices2 <- type_indices[c(TRUE, FALSE)]
NAMark_indices <- which(str_detect(type_NAMark, pattern = "Senate"))

blank_chr_500 <- vector(mode = "character", length = 500)
NAFill_55 <- rep("Treaty Type: Other", 55)

blank_chr_500[NAMark_indices] = NAFill_55
blank_chr_500[type_indices2] = type_half
# blank_chr_500[blank_chr_500 != ""]

# Making vectors for the data frame

treaty1_title <- treaty1_names[c(TRUE, FALSE)]
treaty1_document <- treaty1_names[c(FALSE, TRUE)]
treaty1_pres_date <- str_subset(treaty1_notext_7spaces,
                                pattern = "Date Received from President")
treaty1_date <- str_subset(treaty1_notext_7spaces,
                           pattern = "Date Received: ")
treaty1_action <- treaty1_action0[c(TRUE, FALSE)]
treaty1_type <- blank_chr_500[blank_chr_500 != ""] %>%
  str_trim()

# Making a data frame for page 1

page1 <- data.frame(treaty1_title, treaty1_document, treaty1_pres_date, 
                    treaty1_date, treaty1_action, treaty1_type) %>%
  rename(title = treaty1_title, document = treaty1_document, 
         date_pres = treaty1_pres_date, date = treaty1_date, 
         senate_action = treaty1_action, topic = treaty1_type) %>%
  select(-date_pres) %>%
  mutate(topic = str_replace(topic, "Treaty Topic: ", "")) %>%
  mutate(topic = str_replace(topic, "Treaty Type: ", "")) %>%
  mutate(topic = str_replace(topic, "Other", "NA")) %>%
  mutate(date = str_replace(date, "Date Received: ", ""))

page1 <- page1[c(1, 2, 3, 5, 4)]
```

## Scraping Data from Congress.gov (Page 2)
```{r}
# Writing a function
create_row_from_treaty = function(treaty) {
  title = treaty %>%
    xml_find_first("span[@class='result-heading']") %>%
    html_text() %>%
    str_trim()
  
  document = treaty %>%
    xml_find_first("span[@class='result-title']") %>%
    html_text() %>%
    str_trim()
  
  items_names = treaty %>%
    xml_find_all("span[@class='result-item']/strong") %>%
    html_text() %>%
    str_trim() %>%
    str_sub(end = -2)
  
  items_content = treaty %>%
    xml_find_all("span[@class='result-item']") %>%
    html_text() %>%
    str_trim() %>%
    str_sub(str_length(items_names) + 2) %>%
    str_trim()
  
  pmap_dfc(list(column_names = c("title", "document", items_names),
                row_content = c(title, document, items_content)),
           ~ tibble(!!.x := .y))
}

# Webscraping
url2 <- paste0("https://www.congress.gov/search?q=",
               "{%22source%22:%22treaties%22}", 
               "&searchResultViewType=expanded&pageSort=", 
               "actionAsc&pageSize=250&page=2")
url2_treaty <- read_html(url2)

page2_treaties_all <- url2_treaty %>%
  xml_find_all('//*[@id="main"]/ol/li[@class = "expanded"]')

# Making Table
treaties2 = page2_treaties_all %>%
  map_dfr(create_row_from_treaty)

page2 <- treaties2 %>%
  clean_names() %>%
  select(-text_of_treaty_document) %>%
  rename(date = date_received_from_president, topic = treaty_topic, 
         senate_action = latest_senate_action)
```

## Scraping Data from Congress.gov (Page 3)
```{r}
# Website scraping
url3 <- paste0("https://www.congress.gov/search?q=", 
               "{%22source%22:%22treaties%22}", 
               "&searchResultViewType=expanded&pageSort=",
               "actionAsc&pageSize=250&page=3")
url3_treaty <- read_html(url3)

page3_treaties_all <- url3_treaty %>%
  xml_find_all('//*[@id="main"]/ol/li[@class = "expanded"]')

# Making Table
treaties3 = page3_treaties_all %>%
  map_dfr(create_row_from_treaty)

page3 <- treaties3 %>%
  clean_names() %>%
  select(-text_of_treaty_document) %>%
  rename(date = date_received_from_president, topic = treaty_topic, 
         senate_action = latest_senate_action)
```

## Scraping Data from Congress.gov (Page 4)
```{r}
# Website scraping
url4 <- paste0("https://www.congress.gov/search?q=",
               "{%22source%22:%22treaties%22}", 
               "&searchResultViewType=expanded&pageSort=", 
               "actionAsc&pageSize=250&page=4")
url4_treaty <- read_html(url4)

page4_treaties_all <- url4_treaty %>%
  xml_find_all('//*[@id="main"]/ol/li[@class = "expanded"]')

# Making Table
treaties4 = page4_treaties_all %>%
  map_dfr(create_row_from_treaty)

page4 <- treaties4 %>%
  clean_names() %>%
  select(-text_of_treaty_document) %>%
  rename(date = date_received_from_president, topic = treaty_topic, 
         senate_action = latest_senate_action)
```

## Combining pages to form a single table
```{r}
all_treaties_v1 <- rbind(page1, page2, page3, page4)
all_treaties_v2 <- bind_rows(page1, page2, page3, page4)

# Cleaning table
cleaned_treaties <- all_treaties_v1 %>%
  mutate(topic = str_replace_na(topic, replacement = "NA")) %>%
  mutate(document = str_replace(document, 
                                "Senate Consideration of Treaty Document",
                                "Treaty Document:")) %>%
  mutate(date = as.Date(date, format = "%m/%d/%Y"))
```

## Table Experimentation
```{r}
c_treaties_y <- cleaned_treaties %>%
  mutate(year = format(date, "%Y")) %>%
  mutate(year = as.integer(year))

years_1949_2020 <- tibble(year = 1949:2020)

presidents_1949_2020 <- c(rep("Truman", 4), rep("Eisenhower", 8), 
                          rep("Kennedy", 2), rep("Kennedy/\nJohnson", 1),
                          rep("Johnson", 5), rep("Nixon", 5), 
                          rep("Nixon/\nFord", 1), rep("Ford", 2), 
                          rep("Carter", 4), rep("Reagan", 8), 
                          rep("H.W. Bush", 4), rep("Clinton", 8), 
                          rep("W. Bush", 8), rep("Obama", 8), rep("Trump", 4))

congresses_1949_2020 <- c(rep(81:116, 2)) %>% 
  sort()

government_1949_2020 <- years_1949_2020 %>% 
  mutate(president = presidents_1949_2020) %>%
  mutate(pres_party = case_when(president %in% c("Truman", "Kennedy",
                                                 "Kennedy/\nJohnson", "Johnson",
                                                 "Carter", "Clinton", 
                                                 "Obama") ~ "D", 
                                TRUE ~ "R")) %>% 
  mutate(congress = congresses_1949_2020) %>%
  mutate(congress_party = case_when(congress %in% c(81:82, 84:96, 
                                                    100:103, 110:113) ~ "D", 
                                TRUE ~ "R"))

treaties_government <- full_join(government_1949_2020, c_treaties_y, 
                                 by = "year")

write.csv(treaties_government,"treaties_data_Oct15.csv")
```

## Military Spending
```{r}
d <- read_excel("hist03z1_fy21.xlsx", skip = 1)
spending <- d %>% 
  select(`Superfunction and Function`, "1949":"2019") %>%
  pivot_longer(!`Superfunction and Function`, names_to = "year", 
               values_to = "dollars") %>% 
  filter(`Superfunction and Function` != "In millions of dollars:")

spending$dollars <- as.double(spending$dollars)

estimates <- d %>% 
  select(`Superfunction and Function`, "2020 estimate") %>%
  rename("2020" = "2020 estimate") %>% 
  pivot_longer(!`Superfunction and Function`, names_to = "year", 
               values_to = "dollars") %>% 
  filter(`Superfunction and Function` == "National Defense")

nd_incomplete <- spending %>% 
  filter(`Superfunction and Function` == "National Defense")

nd <- rbind(nd_incomplete, estimates) %>% 
  mutate(year = as.integer(year)) %>% 
  select(year, dollars) %>% 
  filter(year != is.na(year))

treaties_nd_2 <- full_join(treaties_government, nd, by = "year")

write.csv(treaties_nd_2,"treaties_data_Oct22.csv")

treaties_nd_3 <- treaties_nd_2 %>% 
  mutate(action_type = 
           map_chr(senate_action, 
                   ~ case_when(str_detect(., "referred to the Committee") |
                                 str_detect(., "Committee consideration held") |
                                 str_detect(., "Committee on Foreign") |
                                 str_detect(., "Hearings held") ~ 
                                 "Died in Committee",
                               str_detect(., "approved") | 
                                 str_detect(., "agreed to") |
                                 str_detect(., "Approved") |
                                 str_detect(., "Entered into force") |
                                 str_detect(., "Passed Senate without") |
                                 str_detect(., "ratification agreed to") |
                                 str_detect(., "consent to ratification agreed")
                               ~ "Ratified",
                               str_detect(., "Returned to the President") |
                                 str_detect(., "returned to President") |
                                 str_detect(., "returned to the President") ~ 
                                 "Returned to President",
                               str_detect(., "Treaty divided") |
                                 str_detect(., "treaty divided") ~ 
                                 "Returned to President",
                               str_detect(., "Approved, with reservation") ~
                                 "Approved w/ reservation",
                               str_detect(., "Treaty incorporated") ~
                                 "Incorporated into another",
                               is.na(.) ~ "Not Applicable",
                               TRUE ~ "TBC"))) %>% 
  mutate(new_dollars = adjust_for_inflation(dollars, year, "US", 
                                            to_date = 2009))

write.csv(treaties_nd_3,"treaties_data_Oct29.csv")

pres_factors <- c("Truman", "Eisenhower", "Kennedy", "Kennedy/\nJohnson", 
                  "Johnson", "Nixon", "Nixon/\nFord", "Ford", "Carter", 
                  "Reagan", "H.W. Bush", "Clinton", "W. Bush", "Obama", "Trump")

treaties_nd_4 <- treaties_nd_3 %>% 
  mutate(president = factor(president, pres_factors))

write.csv(treaties_nd_4,"treaties_data_Nov3.csv")
```

## Graph Experimentation
```{r}
cleaned_treaties %>%
  mutate(year = format(date, "%Y")) %>%
  group_by(year, topic) %>%
  summarize(n(), .groups = "drop_last") %>%
  ggplot(aes(x = year, fill = topic)) +
  geom_bar() +
  scale_fill_discrete(name = "Treaty Topic", 
                      labels = c("Ag", "AC", "Av", "Cm", "Cn", "DS&A", "Dr", 
                                 "En", "Ex", "Ex&CA", "F&W", "HR", "IP/C", "IL", 
                                 "IL&O", "In", "La", "MB&C", "MLA", "NA", 
                                 "S&MP", "Ta", "Tel", "Ter", "T/P", "UN")) +
  theme_bw() +
  #theme(legend.position = "top") +
  theme(axis.text.x = element_text(size = 5))
```

